In [ ]:
import numpy as np
from ortools.linear_solver import pywraplp

In [10]:
with open("../data/input.txt") as f:
# with open("./data/test.txt") as f:
    n, m, bat_cap, T = [int(i) for i in f.readline().strip().split()] # |V|, |E|, S, T

    build_cost, recharge, profit = [int(i) for i in f.readline().strip().split()] # C, E, P

    # edge_list = [tuple([int(i) for i in f.readline().strip().split()]) for _ in range(m)] # E
    
    dist = np.ndarray((n, n), dtype=np.float32)

    for i in range(m):
        u, v, cost = f.readline().strip().split()
        
        u = int(u) - 1
        v = int(v) - 1
        cost = float(cost)

        dist[u, v] = cost
        dist[v, u] = cost
        dist[u, u] = 0


    demand = [int(i) for i in f.readline().strip().split()] # D



print(n, m, bat_cap, T)
print(build_cost, recharge, profit)
# print(edge_list)
print(dist)
print(demand)

115 6555 50 24
1000 10 5
[[   0.   4192.11 2186.05 ... 2905.89 1596.97  888.63]
 [4192.11    0.   2623.93 ... 1744.76 2771.06 3216.65]
 [2186.05 2623.93    0.   ... 1597.19  645.69 1394.53]
 ...
 [2905.89 1744.76 1597.19 ...    0.   1628.17 2073.76]
 [1596.97 2771.06  645.69 ... 1628.17    0.    816.92]
 [ 888.63 3216.65 1394.53 ... 2073.76  816.92    0.  ]]
[11, 11, 11, 7, 18, 17, 16, 12, 16, 12, 15, 16, 9, 10, 18, 10, 23, 12, 15, 17, 12, 12, 11, 22, 14, 17, 16, 6, 16, 17, 13, 22, 22, 8, 14, 10, 17, 13, 13, 12, 19, 17, 15, 8, 23, 18, 22, 25, 23, 21, 20, 20, 15, 19, 26, 17, 13, 27, 17, 5, 10, 15, 21, 15, 11, 16, 8, 10, 16, 24, 18, 12, 15, 18, 24, 10, 8, 23, 17, 17, 22, 28, 24, 21, 18, 15, 24, 13, 27, 11, 8, 13, 14, 12, 17, 18, 10, 11, 8, 16, 13, 13, 19, 13, 12, 21, 18, 14, 17, 25, 21, 14, 15, 16, 12]


$$
\begin{align*}
    \argmin_{f \in \mathbb{N}^{{\left|V\right|^2}T}}&\sum_{t = 0}^{T - 1}\sum_{i = 0}^{|V| - 1}\left[\alpha\left(D_i - \sum_{j = 0}^{|V| - 1}f_{ijt} \right) + \beta\sum_{j = 0}^{|V| - 1}\left(f_{ijt}L_{ij}\right) \right] \\\\
    \text{s.t.}& \sum_{j = 0}^{|V| - 1}f_{ijt}\leq I_{jt},&\quad \forall i \in V,\ \forall t \in T \\
    & I_{it} = I_{i(t - 1)} - \sum_{j = 0}^{|V| - 1}f_{ij(t - 1)} + E,&\quad \forall i \in V,\ \forall t \in T \\
    & 0 \leq I_{it} \leq S,&\quad\forall i \in V,\ \forall t \in T \\
    & I_{i0} = S,&\quad\forall i \in V \\
    & 0 \leq f_{ijt},&\quad\forall j \in \left\{v | v \in V, x_v = 1 \right\},\ \forall i \in V,\ \forall t \in T \\
    & 0 = f_{ijt},&\quad\forall j \in \left\{v | v \in V, x_v \neq 1 \right\},\ \forall i \in V,\ \forall t \in T \\
\end{align*}
$$

$$
\begin{align*}
    \argmax_{x}&\ P\left(\sum_{t = 0}^{T - 1}\sum_{i = 0}^{|V| - 1}\sum_{j = 0}^{|V| - 1}f^*_{ijt}\right) - C\sum_{i = 0}^{|V| - 1}x_i\\
    \text{s.t.} &\ x \in \left\{0, 1\right\}^{\left|V\right|}
\end{align*}

$$